version: '3'

services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=media_admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DATABASE=media_server
    ports:
      - 5432:5432
    volumes:
      - postgres_data: /var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - 6379:6379

  master-ops-server:
    image: master-ops-server
    build: ./servers/master-ops-server/
    environment:
      PORT: 80
      NODE_ENV: production
    ports:
      - 80:8080
    depends_on:
      - postgres
      - redis

  auth-server:
    image: auth-server
    build: ./servers/auth-server
    environment:
      PORT: 80
    ports:
      - 80:8081
    depends_on:
      - postgres

volumes:
  postgres_data:
    external:
      name: postgres_data
