version: '3'
services:
  postgres:
    image: postgres
  redis:
    image: redis
  master-ops-server:
    image: master-ops-server
    build: ./servers/master-ops-server/
    environment:
      PORT: 8080
      NODE_ENV: production
    ports:
      - 8080
    depends_on:
      - postgres
      - redis
