version: '3'

services:

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=media_server
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - backend

  redis:
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - backend

  # nginx:
  #    image: nginx

  master-ops-server:
    image: master-ops-server
    build: ./servers/master-ops-server/
    environment:
      PORT: 80
      NODE_ENV: production
    ports:
      - 8081:80
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    volumes:
      - ./servers/master-ops-server/:/var/app/
    networks:
      - frontend
      - backend

  auth-server:
    image: auth-server
    build: ./servers/auth-server
    environment:
      PORT: 80
    ports:
      - 8082:80
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./servers/auth-server/:/var/app/
    networks:
      - frontend
      - backend

  streaming-server:
    image: streaming-server
    build: ./servers/streaming-server
    ports:
      - 8083:80
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./servers/streaming-server/:/var/app/
    networks:
      - frontend
      - backend

  client-app:
    image: client-app
    build: ./client
    ports:
      - 8084:3000
    depends_on:
      - auth-server
      - streaming-server
      - master-ops-server
    restart: unless-stopped
    volumes:
      - ./client/:/var/app/
    networks:
      - frontend

volumes:
  postgres_data: null

networks:
  frontend:
    internal: false
  backend:
    internal: true
